// <auto-generated />
using System;
using MDH.OrchestrationService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MDH.OrchestrationService.Persistence.Migrations;

[DbContext(typeof(WarehouseDbContext))]
partial class WarehouseDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("MDH.OrchestrationService.Persistence.Entities.DimListing", b =>
        {
            b.Property<Guid>("ListingId").HasColumnType("uniqueidentifier");
            b.Property<decimal>("Bathrooms").HasColumnType("decimal(4,1)");
            b.Property<int>("Bedrooms").HasColumnType("int");
            b.Property<string>("ExternalId").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<DateTime>("FirstSeenAt").HasColumnType("datetime2");
            b.Property<bool>("IsActive").HasColumnType("bit");
            b.Property<DateTime>("LastUpdatedAt").HasColumnType("datetime2");
            b.Property<string>("Operator").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<int>("Sqft").HasColumnType("int");
            b.Property<string>("StreetAddress").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
            b.Property<int>("SubmarketId").HasColumnType("int");
            b.Property<string>("Unit").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("ListingId").HasName("PK_dim_listing");
            b.HasIndex("ExternalId").HasDatabaseName("IX_dim_listing_ExternalId");
            b.HasIndex("SubmarketId").HasDatabaseName("IX_dim_listing_SubmarketId");
            b.ToTable("dim_listing", "warehouse");
        });

        modelBuilder.Entity("MDH.OrchestrationService.Persistence.Entities.DimSubmarket", b =>
        {
            b.Property<int>("SubmarketId").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmarketId"));
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("Region").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("State").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("SubmarketId").HasName("PK_dim_submarket");
            b.ToTable("dim_submarket", "warehouse");
        });

        modelBuilder.Entity("MDH.OrchestrationService.Persistence.Entities.FactAnomaly", b =>
        {
            b.Property<Guid>("AnomalyId").HasColumnType("uniqueidentifier");
            b.Property<decimal>("AskingRent").HasColumnType("decimal(10,2)");
            b.Property<DateTime>("DetectedAt").HasColumnType("datetime2");
            b.Property<string>("FlagReason").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<bool>("IsResolved").HasColumnType("bit");
            b.Property<Guid>("ListingId").HasColumnType("uniqueidentifier");
            b.Property<decimal>("StdDev").HasColumnType("decimal(10,2)");
            b.Property<decimal>("SubmarketAvgRent").HasColumnType("decimal(10,2)");
            b.Property<decimal>("ZScore").HasColumnType("decimal(6,3)");
            b.HasKey("AnomalyId").HasName("PK_fact_anomaly");
            b.HasIndex("ListingId").HasDatabaseName("IX_fact_anomaly_ListingId");
            b.ToTable("fact_anomaly", "warehouse");
        });

        modelBuilder.Entity("MDH.OrchestrationService.Persistence.Entities.FactDailyRent", b =>
        {
            b.Property<long>("FactId").ValueGeneratedOnAdd().HasColumnType("bigint");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FactId"));
            b.Property<decimal>("AskingRent").HasColumnType("decimal(10,2)");
            b.Property<decimal>("Concessions").HasColumnType("decimal(10,2)");
            b.Property<decimal>("EffectiveRent").HasColumnType("decimal(10,2)");
            b.Property<DateTime>("LoadedAt").HasColumnType("datetime2");
            b.Property<Guid>("ListingId").HasColumnType("uniqueidentifier");
            b.Property<DateOnly>("RentDate").HasColumnType("date");
            b.Property<decimal>("RentPerSqft").HasColumnType("decimal(6,2)");
            b.HasKey("FactId").HasName("PK_fact_daily_rent");
            b.HasIndex(["ListingId", "RentDate"]).IsUnique().HasDatabaseName("IX_fact_daily_rent_ListingId_RentDate");
            b.ToTable("fact_daily_rent", "warehouse");
        });

        modelBuilder.Entity("MDH.OrchestrationService.Persistence.Entities.FactMarketMetrics", b =>
        {
            b.Property<long>("MetricId").ValueGeneratedOnAdd().HasColumnType("bigint");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MetricId"));
            b.Property<decimal>("AvgRent").HasColumnType("decimal(10,2)");
            b.Property<int>("Bedrooms").HasColumnType("int");
            b.Property<DateTime>("ComputedAt").HasColumnType("datetime2");
            b.Property<DateOnly>("MetricDate").HasColumnType("date");
            b.Property<decimal>("MedianRent").HasColumnType("decimal(10,2)");
            b.Property<decimal>("OccupancyEstimate").HasColumnType("decimal(5,4)");
            b.Property<decimal>("RentPerSqft").HasColumnType("decimal(6,2)");
            b.Property<int>("SampleSize").HasColumnType("int");
            b.Property<int>("SubmarketId").HasColumnType("int");
            b.HasKey("MetricId").HasName("PK_fact_market_metrics");
            b.HasIndex(["SubmarketId", "Bedrooms", "MetricDate"]).IsUnique().HasDatabaseName("IX_fact_market_metrics_SubmarketId_Bedrooms_MetricDate");
            b.ToTable("fact_market_metrics", "warehouse");
        });

        modelBuilder.Entity("MDH.OrchestrationService.Persistence.Entities.DimListing", b =>
        {
            b.HasOne("MDH.OrchestrationService.Persistence.Entities.DimSubmarket", "Submarket")
                .WithMany("Listings")
                .HasForeignKey("SubmarketId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Submarket");
        });

        modelBuilder.Entity("MDH.OrchestrationService.Persistence.Entities.FactAnomaly", b =>
        {
            b.HasOne("MDH.OrchestrationService.Persistence.Entities.DimListing", "Listing")
                .WithMany("Anomalies")
                .HasForeignKey("ListingId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Listing");
        });

        modelBuilder.Entity("MDH.OrchestrationService.Persistence.Entities.FactDailyRent", b =>
        {
            b.HasOne("MDH.OrchestrationService.Persistence.Entities.DimListing", "Listing")
                .WithMany("DailyRents")
                .HasForeignKey("ListingId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Listing");
        });

        modelBuilder.Entity("MDH.OrchestrationService.Persistence.Entities.FactMarketMetrics", b =>
        {
            b.HasOne("MDH.OrchestrationService.Persistence.Entities.DimSubmarket", "Submarket")
                .WithMany("MarketMetrics")
                .HasForeignKey("SubmarketId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Submarket");
        });

        modelBuilder.Entity("MDH.OrchestrationService.Persistence.Entities.DimSubmarket", b =>
        {
            b.Navigation("Listings");
            b.Navigation("MarketMetrics");
        });

        modelBuilder.Entity("MDH.OrchestrationService.Persistence.Entities.DimListing", b =>
        {
            b.Navigation("Anomalies");
            b.Navigation("DailyRents");
        });
#pragma warning restore 612, 618
    }
}
